apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.name }}
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    namespace: {{ .Values.destination.namespace }}
    name: {{ .Values.destination.name }}
  source:
    repoURL: {{ .Values.source.repoURL }}
    path: {{ .Vaules.source.path }}
    targetRevision: {{ .Values.source.targetRevision }}
    helm:
      version: v3
      valueFiles:
        - ../beamline_values.yaml
        - values.yaml
      fileParameters:
      {{-  range .Files.glob{{ "config/*"}}  }}
        - name: global.files.{{ . | replace "." "_dot_" }}
          path: config/{{ . }}
      {{- end -}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # don't restart pods unless there has been a change
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true