apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.destination.name }}-app
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    namespace: {{ .Values.destination.namespace }}
    name: {{ .Values.destination.name }}-svc
  source:
    repoURL: {{ .Values.source.repoURL }}
    path: {{ .Values.source.path }}
    targetRevision: {{ .Values.source.targetRevision }}
    helm:
      version: v3
      valueFiles:
        - ../beamline_values.yaml
        - values.yaml
      {{- if .Values.configFiles }}
      fileParameters:
        {{-  range $name, $path := .Values.configFiles }}
          # TODO change this to global.files.$name for better clarity
          # requires a change to the helm chart
          - name: global.files.{{ $path | replace "." "_dot_" }}
            path: config/{{ $path }}
        {{- end -}}
      {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # don't restart pods unless there has been a change
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true